### ISSUE TITLE
Paper and code consistency

### ISSUE THREAD

**Issue by lla0727** [NgHanWei/Subject-Independent_Meta-Learning_EEG#2]
Hello, taking motor imagery as an example, I would like to ask you which python files correspond to conventional learning, meta-learning and meta-testing in the article? And, does your article mean that the first step is conventional learning and then the second step is meta-learning? How does this look in code? Thank you very much!

**Comment by NgHanWei** [comment]
Hi, meta-learning as a broad principle utilizes conventional learning and meta-learning followed by meta-testing as a whole. In the original meta-learning methodology, the model is first trained conventionally on a known task. Meta-learning is then applied to the model to allow it to learn parameters that let it adapt quickly to a new task. Meta-testing is simply the testing of the meta-trained model with a new task.

You may run train_motor_LOSO_all.py which trains a subject-independent meta-trained model.

**Comment by lla0727** [comment]
In other words, if I want to reproduce the results of your paper on motor imagery, then I need to run this command first:
`python train_motor_LOSO_all.py DATAPATH OUTPATH --meta`
and this command second:
 `python train_motor_adapt_all.py DATAPATH MODELPATH OUTPATH `
This gives you the results in your paper, Subject-Independent Meta-Learning(120 Target Trials):88.70, Subject-Independent Meta-Learning:(48 Target Trials 79.38), right?
If not, could you give me detailed commands for reproducing the motor imagery results?
Thank you very much!
